# docker-compose.yml
version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      target: production
    ports:
      - "4173:4173" # Vite's default preview port
    depends_on:
      - api
